'\" t
.\"     Title: reflect
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: Asciidoctor 2.0.10
.\"      Date: 2022-02-22
.\"    Manual: Reflect Manual
.\"    Source: 
.\"  Language: English
.\"
.TH "REFLECT" "1" "2022-02-22" "" "Reflect Manual"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
reflect \- Instantiate a class with reflection
.SH "SYNOPSIS"
.sp
\fBreflect\fP [\fB\-hV\fP] [\fI<className>\fP]
.SH "DESCRIPTION"
.sp
Instantiate a class with reflection
.SH "OPTIONS"
.sp
\fB\-h\fP, \fB\-\-help\fP
.RS 4
Show this help message and exit.
.RE
.sp
\fB\-V\fP, \fB\-\-version\fP
.RS 4
Print version information and exit.
.RE
.SH "ARGUMENTS"
.sp
[\fI<className>\fP]
.RS 4
The name of the class to instantiate (must have no\-args constructor)
.sp
.if n .RS 4
.nf
Default: java.lang.String
.fi
.if n .RE
.RE